@startwbs
skinparam backgroundcolor transparent
+ <b><color:red>100</color></b> marks
 + Individual Project (iP): <b><color:red>10</color></b> marks
 + Team Project (tP): <b><color:red>65</color></b> marks (previously 45)
  + Design:<b><color:red>5</color></b> marks
  + Implementation: <b><color:red>15</color></b> marks (previously 10)
  + Documentation: <b><color:red>20</color></b> marks (previously 10)
  + QA: <b><color:red>15</color></b> marks (previously 10)
  + Project Management: <b><color:red>10</color></b> marks
 + Exam: <b><color:red>20</color></b> marks (previously 40)
 + Participation: <b><color:red>5</color></b> marks
@endwbs